name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          cache: "yarn"

      # - name: Exporting GITHUB-TOKEN
      #   run: export GITHUB_API_TOKEN=$(security find-generic-password -w -a $USER -D "environment variable" -s "GITHUB_API_TOKEN")

      - name: Get version from Tag
        id: version-from-tag
        run: |
          TAG=${{ github.event.client_payload.tag }}
          echo "VERSION=${TAG#v}" >> $VERSION

      - name: Updating version of tiny-lr
        run: |
          echo ${{steps.version-from-tag.outputs.VERSION}}
          yarn remove tiny-lr &&  yarn add tiny-lr@^${{ steps.version-from-tag.outputs.VERSION }}

      # - name: Updating version of ui-core
      #   run: yarn remove @tinderapp/ui-core &&  yarn add @tinderapp/ui-core@^${{ github.event.client_payload.tag }}

      # - name: Updating version of react
      # run: yarn remove @tinderapp/ui-react &&  yarn add @tinderapp/ui-react@^${{ github.event.client_payload.tag }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: autoUpdateObsidian/${{ github.event.client_payload.tag }}
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: Updated Obsidian Dependencies with v${{ github.event.client_payload.tag }}
          title: "Bump Obsidian Dependencies to ${{ github.event.client_payload.tag }}"
          body: >
            This PR is auto-generated
          labels: |
            Obsidian
